# Generated by Django 5.2.7 on 2025-10-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hospital', 'Hospital'), ('donour', 'Donour'), ('recipient', 'recipient')], default='--Choose Role--', max_length=10),
        ),
    ]
