# Generated by Django 5.2.7 on 2025-10-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0005_bloodstock_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('photo', models.ImageField(upload_to='donor_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('photo', models.ImageField(upload_to='donor_photos/')),
            ],
        ),
    ]
