# Generated by Django 5.2.7 on 2025-10-28 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0009_alter_recipientdetails_photo_hospitaldetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='phonenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^(\\+\\d{1,3})?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='phonenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^(\\+\\d{1,3})?(\\d{7}|\\d{10})$')]),
        ),
        migrations.AlterField(
            model_name='recipientdetails',
            name='phonenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^(\\+\\d{1,3})?\\d{10}$')]),
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
