# Generated by Django 5.2.7 on 2025-10-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0011_donorrequestappointment_delete_donationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetails',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
