# Generated by Django 5.2.7 on 2025-10-31 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0012_donordetails_is_eligible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('donor', 'Donor'), ('recipient', 'Recipient')], default='recipient', max_length=10),
        ),
        migrations.CreateModel(
            name='DonorEligibilityTestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField(help_text='Age must be between 18 and 60 years.')),
                ('weight', models.FloatField(help_text='Weight must be at least 50 kg.')),
                ('hemoglobin_level', models.FloatField(help_text='Hemoglobin level in g/dL.')),
                ('last_donation_date', models.DateField(blank=True, help_text='Leave blank if this is your first donation.', null=True)),
                ('has_disease', models.BooleanField(default=False, help_text='Do you currently have any infectious or chronic disease?')),
                ('on_medication', models.BooleanField(default=False, help_text='Are you currently on any medication?')),
                ('had_surgery_recently', models.BooleanField(default=False, help_text='Have you undergone any surgery recently?')),
                ('passed', models.BooleanField(default=False)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Eligibility Test',
                'verbose_name_plural': 'Donor Eligibility Tests',
                'ordering': ['-test_date'],
            },
        ),
    ]
