# Generated by Django 5.2.7 on 2025-10-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0013_alter_profile_role_donoreligibilitytestform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorrequestappointment',
            name='hospital',
        ),
    ]
