# Generated by Django 5.2.7 on 2025-11-01 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0014_remove_donorrequestappointment_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donordetails',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='donordetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='donordetails',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='donoreligibilitytestform',
            name='age',
        ),
        migrations.RemoveField(
            model_name='donorrequestappointment',
            name='additional_notes',
        ),
        migrations.AddField(
            model_name='donordetails',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donoreligibilitytestform',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
