# Generated by Django 5.2.7 on 2025-11-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0015_remove_donordetails_dob_remove_donordetails_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
