# Generated by Django 5.2.7 on 2025-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0018_hospitalbloodrequestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
