# Generated by Django 5.2.7 on 2025-11-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0019_hospitaldetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientdetails',
            name='weight',
        ),
    ]
