# Generated by Django 5.2.7 on 2025-11-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0021_adminnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalbloodrequestform',
            old_name='recipient',
            new_name='hospital',
        ),
    ]
