# Generated by Django 5.2.7 on 2025-11-06 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0022_rename_recipient_hospitalbloodrequestform_hospital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HospitalBloodRequestForm',
            new_name='HospitalBloodRequest',
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RecipientBloodRequestForm',
        ),
    ]
