# Generated by Django 5.2.7 on 2025-11-08 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0026_recipientbloodrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonorEligibilityTestForm',
            new_name='DonorEligibilityTest',
        ),
        migrations.RenameField(
            model_name='bloodstock',
            old_name='bloodgroup',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='donordetails',
            old_name='bloodgroup',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='donordetails',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='hospitaldetails',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='recipientdetails',
            old_name='bloodgroup',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='recipientdetails',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
