# Generated by Django 5.2.7 on 2025-11-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0028_hospitalnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
