# Generated by Django 5.2.7 on 2025-11-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0029_alter_recipientdetails_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldetails',
            name='photo',
        ),
    ]
