# Generated by Django 5.2.7 on 2025-11-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0032_donornotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donoreligibilitytest',
            name='hemoglobin_level',
        ),
        migrations.DeleteModel(
            name='DonorNotification',
        ),
    ]
