# Generated by Django 5.2.7 on 2025-11-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0034_alter_hospitalbloodrequest_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodstock',
            old_name='unit',
            new_name='units',
        ),
    ]
