# Generated by Django 5.2.7 on 2026-01-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0036_recipientbloodrequest_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('hospital', 'Hospital'), ('recipient', 'Recipient')], default='recipient', max_length=10),
        ),
    ]
